---
langs: [fr_FR, en_US]
baseurl: "/Temperature" # the subpath of your site, e.g. /blog
url: "/" # the base hostname & protocol for your site
sass:
  sass_dir: assets/css
  style: compressed
markdown: kramdown
permalink: /404.html
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
exclude:
- vendor
plugins:
- jekyll-paginate
- jekyll-seo-tag
title: "Documentations des plugins et widget de Edualc"
description: "Ceci est la documentation du plugin Tendance baro de la solution domotique Jeedom."
author: "JAG"
image: https://doc.jeedom.com/img/logo.png
forum: https://community.jeedom.com
